In [1]:
import cv2
import numpy as np

In [15]:
image_path = "path_to_your_image.jpg"
image_rgb = cv2.imread('wallpaper2.jpg')
image_rgb

array([[[ 64,  96, 161],
        [ 52,  84, 149],
        [ 47,  79, 144],
        ...,
        [ 47,  65,  28],
        [ 43,  61,  24],
        [ 44,  62,  25]],

       [[ 48,  78, 143],
        [ 34,  65, 128],
        [ 32,  63, 126],
        ...,
        [ 43,  61,  24],
        [ 44,  62,  25],
        [ 48,  66,  29]],

       [[ 54,  82, 146],
        [ 37,  66, 127],
        [ 27,  56, 117],
        ...,
        [ 42,  59,  25],
        [ 46,  63,  29],
        [ 55,  72,  38]],

       ...,

       [[100, 133, 202],
        [107, 140, 209],
        [111, 144, 213],
        ...,
        [ 39,  46,  55],
        [ 38,  46,  53],
        [ 34,  42,  49]],

       [[102, 135, 204],
        [108, 141, 210],
        [112, 145, 214],
        ...,
        [ 34,  39,  48],
        [ 39,  45,  52],
        [ 35,  41,  46]],

       [[106, 139, 208],
        [106, 139, 208],
        [106, 139, 208],
        ...,
        [ 32,  35,  43],
        [ 40,  46,  53],
        [ 37,  43,  48]]

In [14]:
image_gray = cv2.cvtColor(image_rgb, cv2.COLOR_BGR2GRAY)
image_gray

array([[ 84, 106, 137, ...,  51,  35,  52],
       [ 77,  77,  74, ...,  39,  43,  49],
       [ 53,  56,  69, ...,  57,  42,  46],
       ...,
       [157, 150, 157, ...,  42,  47,  42],
       [156, 151, 153, ...,  44,  42,  38],
       [157, 149, 152, ...,  45,  41,  62]], dtype=uint8)

In [16]:
image_inverted = cv2.bitwise_not(image_gray)
image_inverted

array([[171, 149, 118, ..., 204, 220, 203],
       [178, 178, 181, ..., 216, 212, 206],
       [202, 199, 186, ..., 198, 213, 209],
       ...,
       [ 98, 105,  98, ..., 213, 208, 213],
       [ 99, 104, 102, ..., 211, 213, 217],
       [ 98, 106, 103, ..., 210, 214, 193]], dtype=uint8)

In [17]:
image_blurred = cv2.GaussianBlur(image_inverted, (111, 111), 0)
image_blurred

array([[188, 188, 188, ..., 228, 228, 228],
       [188, 188, 188, ..., 228, 228, 228],
       [188, 188, 188, ..., 228, 228, 228],
       ...,
       [102, 102, 102, ..., 215, 215, 215],
       [102, 102, 102, ..., 215, 215, 215],
       [102, 102, 102, ..., 215, 215, 215]], dtype=uint8)

In [6]:
pencil_sketch = cv2.divide(image_gray, 255 - image_blurred, scale=256.0)

In [7]:
pencil_sketch = cv2.resize(pencil_sketch, (500, 300))
image_rgb = cv2.resize(image_rgb, (500, 300))

In [12]:
cv2.imshow("Original Image", image_rgb)
cv2.imshow("Pencil Sketch", pencil_sketch)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
output_path = "pencil_sketch.jpg"
cv2.imwrite(output_path, pencil_sketch)

True